### ISSUE TITLE
Fetch and cache User data

### ISSUE THREAD

**Issue by alvinmarshall** [Bik-KrlvnOrg/sms_client#8]
## Task
- [x] Implement the api service for the issue
- [x] Implement the cache system.

## Acceptance criteria
- [x] should validate already saved user offline
